// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaobaoAuthorization.EntityFrameworkCore;

namespace TaobaoAuthorization.Migrations.TaobaoAuthorizedDb
{
    [DbContext(typeof(TaobaoAuthorizedDbContext))]
    [Migration("20181226012909_TaobaoAuthed_Init")]
    partial class TaobaoAuthed_Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TaobaoAuthorization.Authorizations.AuthorizedInfo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<long>("AppKey");

                    b.Property<string>("AuthState")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreationTime");

                    b.Property<long?>("CreatorUserId");

                    b.Property<DateTime>("ExpiresTime");

                    b.Property<DateTime?>("LastModificationTime");

                    b.Property<long?>("LastModifierUserId");

                    b.HasKey("Id");

                    b.HasIndex("AppKey", "AuthState")
                        .IsUnique();

                    b.ToTable("AuthorizedInfos");
                });
#pragma warning restore 612, 618
        }
    }
}
